document.addEventListener('DOMContentLoaded', () => {
    // Determine API Base URL based on environment
    const isLocalhost = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';
    const API_BASE = isLocalhost ? 'http://127.0.0.1:5000' : 'https://tailor-backend-glqh.onrender.com'; // REPLACE with your actual Render URL
    // 1. Video Scroll Animation Logic
    const canvas = document.getElementById('video-canvas');
    const context = canvas.getContext('2d');
    const videoContainer = document.getElementById('video-container');

    // Specify the number of frames generated by FFmpeg
    const frameCount = 120;

    // Create an aray to hold all images to preload them
    const images = [];
    const airpods = {
        frame: 0
    };

    // Preload all frames
    let framesLoaded = 0;
    for (let i = 1; i <= frameCount; i++) {
        const img = new Image();
        // ffmpeg outputs padding like frame_0001.jpg
        const frameIndex = i.toString().padStart(4, '0');
        img.src = `assets/frames/frame_${frameIndex}.jpg`;
        images.push(img);

        img.onload = () => {
            framesLoaded++;
            // Once the first image is loaded, draw it so canvas isn't blank
            if (i === 1) {
                renderFrame(images[0]);
            }
        };
    }

    // Adjust canvas size to window
    function resizeCanvas() {
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        if (images[airpods.frame]) {
            renderFrame(images[airpods.frame]);
        }
    }

    window.addEventListener('resize', resizeCanvas);
    resizeCanvas();

    function renderFrame(img) {
        if (!img) return;

        // Covering canvas gracefully without squishing (object-fit cover equivalent)
        const canvasAspect = canvas.width / canvas.height;
        const imgAspect = img.width / img.height;
        let renderWidth, renderHeight, xStart, yStart;

        if (canvasAspect > imgAspect) {
            // Canvas is wider than image aspect ratio
            renderWidth = canvas.width;
            renderHeight = canvas.width / imgAspect;
            xStart = 0;
            yStart = (canvas.height - renderHeight) / 2;
        } else {
            // Canvas is taller than image aspect ratio
            renderHeight = canvas.height;
            renderWidth = canvas.height * imgAspect;
            yStart = 0;
            xStart = (canvas.width - renderWidth) / 2;
        }

        // Clear and draw
        context.clearRect(0, 0, canvas.width, canvas.height);
        context.drawImage(img, xStart, yStart, renderWidth, renderHeight);
    }

    // Scroll event listener
    window.addEventListener('scroll', () => {
        // Calculate scroll progress within the video container
        const containerRect = videoContainer.getBoundingClientRect();

        // We only care about scrolling while the container is in or scrolling through viewport
        // container is 300vh, we scroll 200vh effectively.
        const scrollTop = -containerRect.top; // How far we've scrolled past top of container
        const maxScrollTop = videoContainer.scrollHeight - window.innerHeight;

        // Calculate fraction
        let scrollFraction = scrollTop / maxScrollTop;
        // Clamp between 0 and 1
        scrollFraction = Math.max(0, Math.min(1, scrollFraction));

        // Determine which frame corresponds to this scroll fraction
        const frameIndex = Math.min(
            frameCount - 1,
            Math.floor(scrollFraction * frameCount)
        );

        // Update state and render
        if (frameIndex !== airpods.frame && framesLoaded > frameIndex) {
            airpods.frame = frameIndex;
            // Native requestAnimationFrame for smooth drawing
            requestAnimationFrame(() => renderFrame(images[frameIndex]));
        }
    });

    // 2. Fetch Products
    const productsGrid = document.getElementById('products-grid');

    // Modal Elements
    const modal = document.getElementById('product-modal');
    const modalImg = document.getElementById('modal-image');
    const modalTitle = document.getElementById('modal-title');
    const modalDesc = document.getElementById('modal-desc');
    const modalPrice = document.getElementById('modal-price');
    const modalWhatsapp = document.getElementById('modal-whatsapp');
    const closeModal = document.querySelector('.close-modal');

    function openProductModal(product, whatsappNumber, shopName) {
        const fullImgUrl = product.image_url && product.image_url.startsWith('/') ? API_BASE + product.image_url : product.image_url;
        modalImg.src = fullImgUrl || 'https://via.placeholder.com/400x500/1e1e1e/d4af37?text=No+Image';
        modalTitle.textContent = product.name;
        modalDesc.textContent = product.description || 'Exclusive tailored piece.';
        modalPrice.textContent = `₹${product.price.toFixed(2)}`;

        const message = `Hello ${shopName}! I am interested in this product: ${product.name}.`;
        modalWhatsapp.href = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;

        modal.style.display = 'flex';
        // Force reflow
        modal.offsetHeight;
        modal.classList.add('show');
        document.body.style.overflow = 'hidden'; // Prevent scrolling
    }

    function closeProductModal() {
        modal.classList.remove('show');
        setTimeout(() => {
            modal.style.display = 'none';
            document.body.style.overflow = 'auto';
        }, 400);
    }

    closeModal.addEventListener('click', closeProductModal);
    window.addEventListener('click', (e) => {
        if (e.target === modal) closeProductModal();
    });
    window.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && modal.classList.contains('show')) closeProductModal();
    });

    // We try to fetch from flask backend
    fetch(`${API_BASE}/api/products`)
        .then(response => response.json())
        .then(data => {
            productsGrid.innerHTML = ''; // Clear loading state

            const shopDetails = data.shop_details || {};
            const whatsappNumber = shopDetails.whatsapp_number || '919769215219';
            const shopName = shopDetails.shop_name || 'Raj Tailors';

            if (data.products && data.products.length > 0) {
                data.products.forEach((product, index) => {
                    const card = document.createElement('div');
                    // Add fade-in and a slightly staggered transition delay
                    card.className = 'product-card fade-in';
                    card.style.transitionDelay = `${(index % 3) * 0.15}s`;

                    const imgUrl = product.image_url && product.image_url.startsWith('/') ? API_BASE + product.image_url : (product.image_url || 'https://via.placeholder.com/400x500/1e1e1e/d4af37?text=No+Image');

                    card.innerHTML = `
                        <div class="img-wrapper">
                            <img src="${imgUrl}" alt="${product.name}" class="product-image">
                        </div>
                        <div class="product-info">
                            <h3 class="product-title">${product.name}</h3>
                            <p class="product-desc">${product.description || 'Exclusive tailored piece.'}</p>
                            <p class="product-price">₹${product.price.toFixed(2)}</p>
                            <a href="https://wa.me/${whatsappNumber}?text=Hello%20${encodeURIComponent(shopName)}!%20I%20am%20interested%20in%20this%20product:%20${encodeURIComponent(product.name)}.%20Check%20it%20out%20here:%20${encodeURIComponent(imgUrl)}" target="_blank" class="btn-whatsapp">Chat on WhatsApp</a>
                        </div>
                    `;
                    productsGrid.appendChild(card);

                    // Click event for the whole product pic
                    const imgWrapper = card.querySelector('.img-wrapper');
                    imgWrapper.addEventListener('click', () => {
                        openProductModal(product, whatsappNumber, shopName);
                    });

                    // Observe the new card
                    observer.observe(card);
                });
            } else {
                productsGrid.innerHTML = '<div class="loading-state">The collection is currently being curated. Check back soon.</div>';
            }
        })
        .catch(error => {
            console.error('Error fetching products:', error);
            productsGrid.innerHTML = '<div class="loading-state" style="color: #ffb4ab;">Could not load collection automatically. Please ensure the backend is running.</div>';
        });

    // 3. Scroll Reveal Animations
    const observerOptions = {
        threshold: 0.1,
        rootMargin: "0px 0px -50px 0px"
    };

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
                // Optional: stop observing once revealed
                observer.unobserve(entry.target);
            }
        });
    }, observerOptions);

    // Observe existing fade-in elements
    document.querySelectorAll('.fade-in').forEach(el => observer.observe(el));
});
