services:
  - type: web
    name: tailor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tailor-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0

databases:
  - name: tailor-db
    plan: free
